:translation-source: sr
:page-lang: sr
= 2. Kako početi sa Mule 4 (praktični fokus)

U ovom poglavlju kreiraćemo naš prvi Mule 4 projekt korak-po-korak, testirati ga lokalno i zatim deployovati u cloud, da bismo osjetili čitav razvojni proces od početka do kraja . Primjer će biti jednostavan “Hello Mule” API koji prihvata HTTP zahtjev i vraća tekstualni odgovor, ali kroz njega ćemo proći ključne korake razvoja integracije.

[mermaid,chapter2-overview-flow,svg]
....
graph LR
A[Create a new Mule project] --> B[Add flow and connectors]
B --> C[Run and test locally]
C --> D[Deploy to CloudHub]
....

Kreiranje novog projekta: Nakon što instaliramo Anypoint Studio i pokrenemo ga (uz odabir radnog prostora – foldera gdje će se čuvati projekti), kreiramo novi Mule projekt (File > New > Mule Project). Dajemo projektu ime, npr. HelloMule, i biramo odgovarajuću Mule runtime verziju (npr. Mule 4.4). Studio će otvoriti prazan projekt sa osnovnom strukturom. U Package Explorer panelu vidimo folder projekta i datoteke (ključna je mule-project.xml konfiguracija projekta). U sredini je Canvas (radna povšina) gdje ćemo grafički graditi flow, a sa desne strane Mule Palette sa komponentama (konektori, moduli). Ispod je Properties Editor za podešavanje detalja komponenti, te Console za logove aplikacije .

[mermaid,chapter2-studio-layout,svg]
....
graph TD
A[Anypoint Studio] --> B[Package Explorer]
A --> C[Canvas]
A --> D[Mule Palette]
A --> E[Properties Editor]
A --> F[Console]
....

Dodavanje flow-a i konektora: Svaka Mule aplikacija se sastoji od jednog ili više flow-ova – sekvenci komponenti koje obrađuju događaje. Kreiraćemo jednostavan flow koji se aktivira HTTP pozivom i vraća statički odgovor. U Mule Palette pronađemo HTTP modul (koji je obično već uključen po defaultu; ako nije, dodaje se preko Add Modules i pretrage Exchange repozitorijuma ). Iz Palette prevučemo komponentu HTTP Listener na Canvas. Studio automatski kreira novi flow čiji je source taj HTTP Listener (označen plavom ikonicom na početku flow-a). HTTP Listener je ulazna tačka – HTTP endpoint koji čeka na HTTP zahtjev na definisanom URL-u i portu, i kada zahtjev stigne, prosljeđuje ga u dalji tok flow-a . U Properties panelu za HTTP Listener, kliknemo na + da konfigurišemo listener. Ostavljamo default Host 0.0.0.0 (što znači sluša na svim interfejsima) i Port 8081 . U polje Path unosimo npr. /hellomule – to je putanja na koju će listener reagovati. Ovom konfiguracijom određujemo da će naš API primati GET/POST zahtjeve na URL http://localhost:8081/hellomule.

Nakon HTTP Listener-a, dodajemo procesorsku komponentu koja će formirati odgovor. Za ovaj jednostavan primjer, iskoristićemo Set Payload komponentu (nalazi se u Core modulu u Palette). Prevlačimo Set Payload na Canvas unutar dijela Process (Studio ga postavlja iza Listener-a). U Properties za Set Payload unosimo u polje Value string "Hello Mule" (treba prethodno odčekirati Expression oznaku fx da bismo unijeli literalni string) . Ova komponenta će jednostavno postaviti tijelo (payload) odgovora na dati tekst. (Napomena: u realnijim scenarijima, ovdje bismo imali niz komponenti koje pozivaju spoljne sisteme, transformišu podatke i sl. – sve to ćemo kasnije obraditi – ali sada ostajemo pri jednostavnom statičkom odgovoru da bi fokus bio na mehanici rada.) Za kraj dodajemo još komponentu Logger (iz Core modula) da ispiše u logu da je flow obradio zahtjev, čisto radi praćenja. U Logger-u možemo podesiti poruku, npr. "Processed request on #[attributes.requestPath]" da vidimo putanju zahtjeva.

[mermaid,chapter2-hello-mule-flow,svg]
....
graph LR
A[HTTP Listener] --> B[Set Payload]
B --> C[Logger]
C --> D[HTTP Response: Hello Mule]
....

Lokalno pokretanje i testiranje: Čuvamo projekat (File > Save All). Sada desnim klikom na Canvas biramo Run project HelloMule . U Console tabu pratimo log – Mule pokreće ugrađeni server i našu aplikaciju. Kada se pojavi poruka DEPLOYED (i status [✔] Deployed), aplikacija radi lokalno . Vrijeme je za test: otvorimo omiljeni REST klijent (npr. Postman) i pošaljemo HTTP GET zahtjev na URL http://localhost:8081/hellomule . Rezultat bi trebalo da bude HTTP 200 OK sa tijelom odgovora "Hello Mule". Ako to dobijemo – uspješno smo razvili i pokrenuli svoju prvu Mule aplikaciju! 🎉 (Napomena: 0.0.0.0 host možemo zamijeniti sa localhost u URL-u; efekat je isti .) Kada završimo testiranje, možemo zaustaviti aplikaciju desnim klikom na Canvas > Stop Project .

[mermaid,chapter2-local-test,svg]
....
sequenceDiagram
    participant U as User/Postman
    participant M as Mule App
    U->>M: GET /hellomule
    M-->>U: 200 OK\n"Hello Mule"
....

Deploy na CloudHub: Sada, hajde da našu aplikaciju “podignemo” u MuleSoft cloud. Potreban nam je MuleSoft Anypoint nalog (može i free trial ako je ovo testni projekt). U Studio-u, u Package Explorer panelu, desni klik na projekat HelloMule > Anypoint Platform > Deploy to CloudHub . Studio će tražiti da unesemo kredencijale za Anypoint Platform (email i lozinka). Zatim biramo Environment – na raspolaganju su npr. Sandbox (predefinisani development environment) ili možemo imati Production environment (za sada biramo Sandbox). Unosimo ime aplikacije kojom će biti dostupna na CloudHub-u, recimo hellomule (mora biti jedinstveno u globalnom kontekstu – Studio će pokazati zeleno ✔ ako je ime slobodno, ili crveno X ako neko već koristi to ime) . Kliknemo Deploy i Studio će početi upload i pokretanje aplikacije u cloud-u. Nakon minut-dva, aplikacija bi trebalo da bude running na CloudHub-u. Možemo to provjeriti prijavom na Anypoint Platform web interfejs (dugme Log in u Studio deployment wizard-u ili ručno otvaranjem browsera) . Na Platformi, idemo u Runtime Manager, biramo env (Sandbox) i trebalo bi da vidimo aplikaciju hellomule u listi. Klikom na nju otvara se dashboard sa detaljima – tu je i URL aplikacije. CloudHub hostuje aplikaciju na URL-u oblika http://imeAplicacije.region.cloudhub.io. Za imeAplicacije koristili smo hellomule, a region može biti npr. us-e2 (Istočni US) ili eu-west-1 (Irska) zavisno od datog environment-a. Studio nam obično prikaže puni URL nakon deploya – recimo http://hellomule.us-e2.cloudhub.io/hellomule . Taj URL sada možemo pozvati iz REST klijenta (ili čak browsera, pošto je GET) – trebalo bi takođe da dobijemo "Hello Mule" odgovor, samo što ovaj put zahtjev ide preko interneta do našeg API-ja na CloudHub-u. Čestitamo! Implementirali smo prvi Mule flow, lokalno ga istestirali i zatim uspješno deployovali u cloud, čime smo prošli čitav ciklus razvoja integracije. 🎉

[mermaid,chapter2-cloudhub-deploy,svg]
....
graph LR
A[Anypoint Studio] --> B[Deploy to CloudHub]
B --> C[Sandbox Environment]
C --> D[CloudHub Application]
D --> E[Runtime Manager]
E --> F[Public URL]
....

(Napomena: Ovaj jednostavni primjer služi za ilustraciju osnovnog postupka. U narednim poglavljima ćemo konceptualno objasniti šta se “iza kulisa” dešava kada Mule aplikacija radi, kako je strukturišemo kompleksnije integracije, kako transformišemo podatke, obrađujemo greške, testiramo i sl., tako da ćete razumjeti zašto je gore navedeni primjer tako napravljen i kako ga unaprijediti.)


* link:https://docs.mulesoft.com/studio/[Anypoint Studio dokumentacija, window="_blank"]
* link:https://anypoint.mulesoft.com/login/signup?apintent=generic[Prijava za CloudHub, window="_blank"]


* link:https://docs.google.com/forms/d/e/1FAIpQLScqvN5p16Rg4oCx7XVekGpv6xR_4v9D_jkpZsoKGVfsljA-zg/viewform?usp=publish-editor[Kratak kviz za provjeru znanja, window="_blank"]