:primary-lang: sr

== 3.1 Upoznavanje sa Anypoint Studio okruženjem

Prilikom kreiranja HelloMule aplikacije susreli smo se sa osnovnim elementima Anypoint Studio okruženja: flow, konektor, procesor, logger, globalna konfiguracija, itd. Bitno je razumjeti da sve što radimo vizuelno u Studio-u zapravo se čuva u pozadini kao XML konfiguracija (tzv. Mule konfiguracijski fajlovi). Svaki flow koji napravimo je zapravo element u XML-u, konektori su specifični XML tag-ovi (npr. <http:listener> za HTTP Listener, <set-payload> za Set Payload, itd.), sa atributima koji odgovaraju onome što smo podesili u Properties panelu. Studio nam sakriva XML detalje i pruža pregledniji prikaz, ali Mule aplikacija se na kraju uvijek svodi na konfiguraciju koju interpretiše Mule runtime. Taj model omogućava da se iste aplikacije mogu pokretati bilo iz Studio-a, bilo u cloud-u, bilo na on-prem serveru – svuda gdje Mule runtime može učitati taj konfiguracioni fajl.

[mermaid,studio-to-runtime-model,svg]
....
graph LR
Developer --> Studio
Studio --> VisualFlow
VisualFlow --> XMLConfig
XMLConfig --> MuleRuntime
MuleRuntime --> Application
....

Pogledajmo ključne komponente našeg primera:

* *Flow:* U HelloMule projektu imamo jedan glavni flow (Studio ga je automatski nazvao flow1 dok ga ne bismo preimenovali). Flow predstavlja sekvencu obrade – sastoji se od source dijela (ulazni endpoint) i process dijela (niz procesa/operacija). U našem slučaju, source je HTTP Listener na localhost:8081/hellomule, a u process dijelu su Set Payload i Logger. Svaki put kad stigne HTTP zahtjev na definisani endpoint, Mule runtime generiše Mule Event i predaje ga ovom flow-u na obradu.

[mermaid,mule-flow-overview,svg]
....
graph LR
HTTP_Request --> HTTP_Listener
HTTP_Listener --> Mule_Flow
Mule_Flow --> Set_Payload
Set_Payload --> Logger
Logger --> HTTP_Response
....

* *Mule Event:* Šta je Mule Event? – To je osnovna jedinica podatka koja prolazi kroz flow. Mule 4 ima pojednostavljeni model poruke gdje svaki Event sadrži message i prateće varijable. Message se dalje sastoji od payload-a (glavnog sadržaja poruke, npr. tijelo HTTP zahtjeva ili odgovor koji gradimo) i atributa (metapodataka – npr. HTTP zaglavlja, query parametri, itd. koji prate payload). Varijable su dodatni podaci koje možemo definisati u toku obrade (lokalne za flow ili globalne) i nisu dio samog message-a. U našem primjeru, HTTP Listener kreira Event čiji početni payload je prazan (jer GET zahtjev nema tijelo osim eventualno query parametara), a atributi sadrže informacije o HTTP zahtjevu (metod, putanju, parametre itd.). Taj Event ulazi u flow: Set Payload mijenja njegov payload u “Hello Mule” (ostali atributi ostaju netaknuti), Logger ispisuje log poruku (može koristiti i atribute, recimo attributes.requestPath), a zatim na kraju flow-a Mule runtime uzima taj Event i formira HTTP odgovor klijentu na osnovu njega (payload ide kao body odgovora, određeni atributi kao status kod, zaglavlja itd.). Važno je shvatiti da Mule Event putuje kroz sve komponente flow-a i one mogu čitati ili mijenjati njegov sadržaj. Drugim riječima, flow je pipeline kroz koji prolazi jedan Event – nema dijeljenja stanja između različitih zahtjeva (svaki novi HTTP request generiše novi Event i dobija svoj tok obrade).

[mermaid,mule-event-structure,svg]
....
graph TD
MuleEvent --> Message
Message --> Payload
Message --> Attributes
MuleEvent --> Variables
....

* *Konektori i operacije:* U našem malom primjeru koristili smo HTTP Listener (konektor za HTTP protokol kao source) i Set Payload (procesorska operacija iz Core modula). Uopšteno, konektor je komponenta koja omogućava interakciju sa nekim spoljnim sistemom ili protokolom. MuleSoft ima ogromnu biblioteku konektora (HTTP, Database, File, JMS, Salesforce, SAP, i stotine drugih). Konektor može biti inbound (kao Listener koji čeka dolazne događaje) ili outbound (kao HTTP Request koji poziva neki vanjski servis ili Database konektor koji izvršava upit). U Studio paleti, inbound konektori su raspoređeni u odjeljak Sources (mogu se postaviti na početak flow-a), dok se ostale komponente vuku u process dio flow-a. U primjeru, HTTP Listener je inbound konektor (source), a Set Payload i Logger su procesori (koji ne komuniciraju sa vanjskim sistemom već vrše interne operacije).

[mermaid,connector-types,svg]
....
graph LR
External_System --> Inbound_Connector
Inbound_Connector --> Mule_Flow
Mule_Flow --> Outbound_Connector
Outbound_Connector --> External_System
....

* *Globalna konfiguracija:* Primijetili smo da smo prilikom dodavanja HTTP Listener-a kreirali HTTP Listener konfiguraciju (globalni element koji sadrži port, host i ostala podešavanja konektora). Ovaj globalni element stoji odvojeno od samog flow-a (u XML-u unutar <config> sekcije) i može se ponovno koristiti. Npr. ako imamo više HTTP Listener-a (na različitim path-ovima) u različitim flow-ovima, svi mogu koristiti istu globalnu HTTP konfiguraciju (isti port). Slično, konektori za bazu podataka imaju globalnu konfiguraciju sa connection stringom, korisnikom/lozinkom itd., koju definišemo jednom i onda je referenciramo iz više flow-ova. Time se postiže centralizacija parametara i lakše podešavanje. U našem projektu HelloMule, globalna konfiguracija je minimalna (HTTP listener config), ali u ozbiljnijim projektima tu će biti definicije za svaki spoljašnji sistem, globalne varijable, itd.

[mermaid,global-config-usage,svg]
....
graph TD
Global_Config --> Flow1
Global_Config --> Flow2
Global_Config --> Flow3
....

*Razumijevanje osnovnih koncepta:* Sada možemo povezati praktične korake sa konceptima:

* Flow je osnovna jedinica aplikacijske logike – sekvenca kojom Mule runtime obrađuje događaj od ulaza do izlaza.
* Event je objekt koji nosi podatke kroz flow (payload + atributi), nastaje iz ulaznog konektora i evoluira kroz proces.
* Konektori omogućuju interakciju s eksternim resursima (ili protokolima); MuleSoft ima preko 200 gotovih konektora i mogućnost pravljenja prilagođenih putem Mule SDK-a ako zatreba.
* Procesori (komponente poput transformacija, filtera, routinga) izvode operacije nad eventom (npr. mijenjaju payload, donose odluke, loguju, bacaju greške…).
* Globalne postavke služe da se parametri (npr. konekcije) definišu centralno i lako mijenjaju za različita okruženja.

Ovdje završava konceptualni pregled našeg prvog Mule projekta. Ključna poruka je da, iako smo u Studio-u radili drag-and-drop, bitno je shvatiti šta se dešava ispod haube. U nastavku ćemo ući dublje u Mule-ove osnovne koncepte – posebno Mule Event model i flow izvršavanje – kako bismo stekli čvrsto razumijevanje za naredne, složenije primjere.

* https://docs.mulesoft.com/mule-runtime/latest/choice-router-concept#xml-configuration[Mule Konfiguracija (XML):]
* https://docs.mulesoft.com/mule-runtime/latest/flow-component[Mule Flow (Source i Process)]
* https://docs.mulesoft.com/mule-runtime/latest/intro-mule-message[Mule Event Model (Payload i Atributi)]
* https://docs.mulesoft.com/connectors/introduction/introduction-to-anypoint-connectors[Mule Konektori i Operacije]
* https://docs.mulesoft.com/mule-runtime/latest/global-elements[Globalna konfiguracija - Global Elements]


* link:https://docs.google.com/forms/d/e/1FAIpQLSeaMdWh5q5o52cV9JoNSFzAHhWUfn-B2rv9hke7e1zWulQI1Q/viewform?usp=publish-editor[Kratak kviz za provjeru znanja, window="_blank"]